<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `ymskj_enewsclass`;");
E_C("CREATE TABLE `ymskj_enewsclass` (
  `classid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `bclassid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `classname` varchar(50) NOT NULL DEFAULT '',
  `sonclass` text NOT NULL,
  `is_zt` tinyint(1) NOT NULL DEFAULT '0',
  `lencord` smallint(6) NOT NULL DEFAULT '0',
  `link_num` tinyint(4) NOT NULL DEFAULT '0',
  `newstempid` smallint(6) NOT NULL DEFAULT '0',
  `onclick` int(11) NOT NULL DEFAULT '0',
  `listtempid` smallint(6) NOT NULL DEFAULT '0',
  `featherclass` text NOT NULL,
  `islast` tinyint(1) NOT NULL DEFAULT '0',
  `classpath` text NOT NULL,
  `classtype` varchar(10) NOT NULL DEFAULT '',
  `newspath` varchar(20) NOT NULL DEFAULT '',
  `filename` tinyint(1) NOT NULL DEFAULT '0',
  `filetype` varchar(10) NOT NULL DEFAULT '',
  `openpl` tinyint(1) NOT NULL DEFAULT '0',
  `openadd` tinyint(1) NOT NULL DEFAULT '0',
  `newline` int(11) NOT NULL DEFAULT '0',
  `hotline` int(11) NOT NULL DEFAULT '0',
  `goodline` int(11) NOT NULL DEFAULT '0',
  `classurl` varchar(200) NOT NULL DEFAULT '',
  `groupid` smallint(6) NOT NULL DEFAULT '0',
  `myorder` smallint(6) NOT NULL DEFAULT '0',
  `filename_qz` varchar(20) NOT NULL DEFAULT '',
  `hotplline` tinyint(4) NOT NULL DEFAULT '0',
  `modid` smallint(6) NOT NULL DEFAULT '0',
  `checked` tinyint(1) NOT NULL DEFAULT '0',
  `firstline` tinyint(4) NOT NULL DEFAULT '0',
  `bname` varchar(50) NOT NULL DEFAULT '',
  `islist` tinyint(1) NOT NULL DEFAULT '0',
  `searchtempid` smallint(6) NOT NULL DEFAULT '0',
  `tid` smallint(6) NOT NULL DEFAULT '0',
  `tbname` varchar(60) NOT NULL DEFAULT '',
  `maxnum` int(11) NOT NULL DEFAULT '0',
  `checkpl` tinyint(1) NOT NULL DEFAULT '0',
  `down_num` tinyint(4) NOT NULL DEFAULT '0',
  `online_num` tinyint(4) NOT NULL DEFAULT '0',
  `listorder` varchar(50) NOT NULL DEFAULT '',
  `reorder` varchar(50) NOT NULL DEFAULT '',
  `intro` text NOT NULL,
  `classimg` varchar(255) NOT NULL DEFAULT '',
  `jstempid` smallint(6) NOT NULL DEFAULT '0',
  `addinfofen` int(11) NOT NULL DEFAULT '0',
  `listdt` tinyint(1) NOT NULL DEFAULT '0',
  `showclass` tinyint(1) NOT NULL DEFAULT '0',
  `showdt` tinyint(1) NOT NULL DEFAULT '0',
  `checkqadd` tinyint(1) NOT NULL DEFAULT '0',
  `qaddlist` tinyint(1) NOT NULL DEFAULT '0',
  `qaddgroupid` text NOT NULL,
  `qaddshowkey` tinyint(1) NOT NULL DEFAULT '0',
  `adminqinfo` tinyint(1) NOT NULL DEFAULT '0',
  `doctime` smallint(6) NOT NULL DEFAULT '0',
  `classpagekey` varchar(255) NOT NULL DEFAULT '',
  `dtlisttempid` smallint(6) NOT NULL DEFAULT '0',
  `classtempid` smallint(6) NOT NULL DEFAULT '0',
  `nreclass` tinyint(1) NOT NULL DEFAULT '0',
  `nreinfo` tinyint(1) NOT NULL DEFAULT '0',
  `nrejs` tinyint(1) NOT NULL DEFAULT '0',
  `nottobq` tinyint(1) NOT NULL DEFAULT '0',
  `ipath` varchar(255) NOT NULL DEFAULT '',
  `addreinfo` tinyint(1) NOT NULL DEFAULT '0',
  `haddlist` tinyint(4) NOT NULL DEFAULT '0',
  `sametitle` tinyint(1) NOT NULL DEFAULT '0',
  `definfovoteid` smallint(6) NOT NULL DEFAULT '0',
  `wburl` varchar(255) NOT NULL DEFAULT '',
  `qeditchecked` tinyint(1) NOT NULL DEFAULT '0',
  `wapstyleid` smallint(6) NOT NULL DEFAULT '0',
  `repreinfo` tinyint(1) NOT NULL DEFAULT '0',
  `pltempid` smallint(6) NOT NULL DEFAULT '0',
  `cgroupid` text NOT NULL,
  `yhid` smallint(6) NOT NULL DEFAULT '0',
  `wfid` smallint(6) NOT NULL DEFAULT '0',
  `cgtoinfo` tinyint(1) NOT NULL DEFAULT '0',
  `bdinfoid` varchar(25) NOT NULL DEFAULT '',
  `repagenum` smallint(5) unsigned NOT NULL DEFAULT '0',
  `keycid` smallint(6) NOT NULL DEFAULT '0',
  `allinfos` int(10) unsigned NOT NULL DEFAULT '0',
  `infos` int(10) unsigned NOT NULL DEFAULT '0',
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`classid`),
  KEY `bclassid` (`bclassid`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8");
E_D("replace into `ymskj_enewsclass` values('1','0','团队风采','','0','25','10','10','0','9','','1','tuanduifengcai','.html','Y-m-d','0','.html','0','1','10','10','10','','0','0','','10','1','1','10','团队风采','0','0','1','news','0','0','2','2','id DESC','newstime DESC','伊美时国际医药科技（北京）有限公司隶属伊美时集团，伊美时集团是一家以健康产业为龙头，涉足生物技术研发，营养保健品及医疗器械生产、推广、等多个领域的综合型集团公司。其下属子公司有伊美时国际医药科技（北京）有限公司，杨凌伊美时公司，西安百姓堂药业、河北同济生物有限公司、伊美时生活连锁店、等多家子公司。伊美时国际医药科技（北京）有限公司成立于2014年，公司座落在美丽文明的古城邯郸，是一家以健康管理为主导，集日用品、功能性纺织品、保健食品、水处理设备、空气净化设备，生产与销售推广为一体的企业。伊美时国际医药科技（北京）有限公司成立至今，其产品已覆盖全国十余个省份，设有伊美时连锁500余家，拥有高级管理人才2000余名。公司凭借优质的产品，专业的销售团队，保持着持续稳定的发展，其市场影响力快速上升。伊美时健康管理有限公司本着“诚信，质量，共赢”的企业理念，以诚信为标准，以品质为核心，以市场为导向，打造中国高端养生第一品牌。伊美时国际医药科技（北京）有限公司以传播绿色养生文化为己任，致力于提高生命品质，公司以孝爱的文化管理团队，以孝爱的团队服务市场，以孝爱的事业造福社会。让你我享受真正的健康好生活。','','1','0','0','0','0','0','0','','0','0','0','伊美时国际医药科技（北京）有限公司，团队风采','9','1','0','0','0','0','','1','0','0','0','','0','0','0','0','','0','0','0','','0','0','0','0','1503803822');");
E_D("replace into `ymskj_enewsclass` values('2','0','资质荣誉','','0','25','10','10','0','10','','1','zizhirongyu','.html','Y-m-d','0','.html','0','1','10','10','10','','0','0','','10','1','1','10','资质荣誉','0','0','1','news','0','0','2','2','id DESC','newstime DESC','伊美时国际医药科技（北京）有限公司隶属伊美时集团，伊美时集团是一家以健康产业为龙头，涉足生物技术研发，营养保健品及医疗器械生产、推广、等多个领域的综合型集团公司。其下属子公司有伊美时国际医药科技（北京）有限公司，杨凌伊美时公司，西安百姓堂药业、河北同济生物有限公司、伊美时生活连锁店、等多家子公司。伊美时国际医药科技（北京）有限公司成立于2014年，公司座落在美丽文明的古城邯郸，是一家以健康管理为主导，集日用品、功能性纺织品、保健食品、水处理设备、空气净化设备，生产与销售推广为一体的企业。伊美时国际医药科技（北京）有限公司成立至今，其产品已覆盖全国十余个省份，设有伊美时连锁500余家，拥有高级管理人才2000余名。公司凭借优质的产品，专业的销售团队，保持着持续稳定的发展，其市场影响力快速上升。伊美时健康管理有限公司本着“诚信，质量，共赢”的企业理念，以诚信为标准，以品质为核心，以市场为导向，打造中国高端养生第一品牌。伊美时国际医药科技（北京）有限公司以传播绿色养生文化为己任，致力于提高生命品质，公司以孝爱的文化管理团队，以孝爱的团队服务市场，以孝爱的事业造福社会。让你我享受真正的健康好生活。','','1','0','0','0','0','0','0','','0','0','0','伊美时国际医药科技（北京）有限公司，资质荣誉','10','1','0','0','0','0','','1','0','0','0','','0','0','0','0','','0','0','0','','0','0','0','0','1503803892');");
E_D("replace into `ymskj_enewsclass` values('3','0','视频展厅','','0','25','10','10','0','11','','1','shipinzhanting','.html','Y-m-d','0','.html','0','1','10','10','10','','0','0','','10','1','1','10','视频展厅','0','0','1','news','0','0','2','2','id DESC','newstime DESC','伊美时国际医药科技（北京）有限公司隶属伊美时集团，伊美时集团是一家以健康产业为龙头，涉足生物技术研发，营养保健品及医疗器械生产、推广、等多个领域的综合型集团公司。其下属子公司有伊美时国际医药科技（北京）有限公司，杨凌伊美时公司，西安百姓堂药业、河北同济生物有限公司、伊美时生活连锁店、等多家子公司。伊美时国际医药科技（北京）有限公司成立于2014年，公司座落在美丽文明的古城邯郸，是一家以健康管理为主导，集日用品、功能性纺织品、保健食品、水处理设备、空气净化设备，生产与销售推广为一体的企业。伊美时国际医药科技（北京）有限公司成立至今，其产品已覆盖全国十余个省份，设有伊美时连锁500余家，拥有高级管理人才2000余名。公司凭借优质的产品，专业的销售团队，保持着持续稳定的发展，其市场影响力快速上升。伊美时健康管理有限公司本着“诚信，质量，共赢”的企业理念，以诚信为标准，以品质为核心，以市场为导向，打造中国高端养生第一品牌。伊美时国际医药科技（北京）有限公司以传播绿色养生文化为己任，致力于提高生命品质，公司以孝爱的文化管理团队，以孝爱的团队服务市场，以孝爱的事业造福社会。让你我享受真正的健康好生活。','','1','0','0','0','0','0','0','','0','0','0','伊美时国际医药科技（北京）有限公司，视频展厅','11','1','0','0','0','0','','1','0','0','0','','0','0','0','0','','0','0','0','','0','0','0','0','1503803946');");

@include("../../inc/footer.php");
?>