<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `ymskj_enewspagetemp`;");
E_C("CREATE TABLE `ymskj_enewspagetemp` (
  `tempid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `tempname` varchar(30) NOT NULL DEFAULT '',
  `temptext` mediumtext NOT NULL,
  PRIMARY KEY (`tempid`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8");
E_D("replace into `ymskj_enewspagetemp` values('1','关于我们','<!DOCTYPE html>\r\n<html lang=\\\\\"zh-CN\\\\\">\r\n<head>\r\n<meta http-equiv=\\\\\"Content-Type\\\\\" content=\\\\\"text/html; charset=utf-8\\\\\" />\r\n<title>[!--pagetitle--]</title>\r\n<meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\" />\r\n<meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/base.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/index.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<script type=\\\\\"text/javascript\\\\\" src=\\\\\"[!--news.url--]skin/default/js/tabs.js\\\\\"></script>\r\n</head>\r\n<body>\r\n[!--temp.header--]\r\n    <section class=\\\\\"center clearfix\\\\\">\r\n        <div class=\\\\\"sec-item left\\\\\" style=\\\\\"width: 19%;\\\\\">\r\n            <div class=\\\\\"sec-item-title\\\\\">\r\n                <img src=\\\\\"[!--news.url--]skin/default/images/yms_08.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;margin-top: 13px;\\\\\">\r\n                <p class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;\\\\\">关于我们 About us</p>\r\n            </div>\r\n            <div class=\\\\\"about-list\\\\\">\r\n                <ul>\r\n                    <li><a href=\\\\\"[!--news.url--]brief.html\\\\\">公司简介</a></li>\r\n                    <li><a href=\\\\\"[!--news.url--]culture.html\\\\\">企业文化</a></li>\r\n                    <li><a href=\\\\\"/tuanduifengcai/\\\\\">团队风采</a></li>\r\n                    <li><a href=\\\\\"/zizhirongyu/\\\\\">资质荣誉</a></li>\r\n                    <li><a href=\\\\\"/shipinzhanting/\\\\\">视频展厅</a></li>\r\n                </ul>\r\n            </div>\r\n            <img src=\\\\\"[!--news.url--]skin/default/images/left.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" style=\\\\\"margin-top: 10px;\\\\\">\r\n        </div>\r\n        <div class=\\\\\"about-right left\\\\\">\r\n            <div class=\\\\\"about-right-title\\\\\">\r\n                <p>[!--pagename--]</p>\r\n            </div>\r\n            <div class=\\\\\"about-content\\\\\">\r\n                [!--pagetext--]\r\n            </div>\r\n            <div class=\\\\\"totop right\\\\\"></div>\r\n        </div>\r\n    </section>\r\n    <ul class=\\\\\"index\\\\\">\r\n        <li></li>\r\n    </ul>\r\n[!--temp.footer--]\r\n</body>\r\n</html>');");
E_D("replace into `ymskj_enewspagetemp` values('3','企业文化','<!DOCTYPE html>\r\n<html lang=\\\\\"zh-CN\\\\\">\r\n<head>\r\n<meta http-equiv=\\\\\"Content-Type\\\\\" content=\\\\\"text/html; charset=utf-8\\\\\" />\r\n<title>[!--pagetitle--]</title>\r\n<meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\" />\r\n<meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/base.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/index.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<script type=\\\\\"text/javascript\\\\\" src=\\\\\"[!--news.url--]skin/default/js/tabs.js\\\\\"></script>\r\n</head>\r\n<body>\r\n[!--temp.header--]\r\n    <section class=\\\\\"center clearfix\\\\\">\r\n        <div class=\\\\\"sec-item left\\\\\" style=\\\\\"width: 19%;\\\\\">\r\n            <div class=\\\\\"sec-item-title\\\\\">\r\n                <img src=\\\\\"[!--news.url--]skin/default/images/yms_08.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;margin-top: 13px;\\\\\">\r\n                <p class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;\\\\\">关于我们 About us</p>\r\n            </div>\r\n            <div class=\\\\\"about-list\\\\\">\r\n                <ul>\r\n                    <li><a href=\\\\\"[!--news.url--]brief.html\\\\\">公司简介</a></li>\r\n                    <li><a href=\\\\\"[!--news.url--]culture.html\\\\\">企业文化</a></li>\r\n                    <li><a href=\\\\\"/tuanduifengcai/\\\\\">团队风采</a></li>\r\n                    <li><a href=\\\\\"/zizhirongyu/\\\\\">资质荣誉</a></li>\r\n                    <li><a href=\\\\\"/shipinzhanting/\\\\\">视频展厅</a></li>\r\n                </ul>\r\n            </div>\r\n            <img src=\\\\\"[!--news.url--]skin/default/images/left.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" style=\\\\\"margin-top: 10px;\\\\\">\r\n        </div>\r\n        <div class=\\\\\"about-right left\\\\\">\r\n            <div class=\\\\\"about-right-title\\\\\">\r\n                <p>[!--pagename--]</p>\r\n            </div>\r\n            <div class=\\\\\"about-content\\\\\">\r\n                [!--pagetext--]\r\n            </div>\r\n            <div class=\\\\\"totop right\\\\\"></div>\r\n        </div>\r\n    </section>\r\n    <ul class=\\\\\"index\\\\\">\r\n        <li></li>\r\n    </ul>\r\n    <ul class=\\\\\"indexx\\\\\">\r\n        <li></li>\r\n    </ul>\r\n[!--temp.footer--]\r\n</body>\r\n</html>');");
E_D("replace into `ymskj_enewspagetemp` values('2','公司简介','<!DOCTYPE html>\r\n<html lang=\\\\\"zh-CN\\\\\">\r\n<head>\r\n<meta http-equiv=\\\\\"Content-Type\\\\\" content=\\\\\"text/html; charset=utf-8\\\\\" />\r\n<title>[!--pagetitle--]</title>\r\n<meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\" />\r\n<meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/base.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/index.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<script type=\\\\\"text/javascript\\\\\" src=\\\\\"[!--news.url--]skin/default/js/tabs.js\\\\\"></script>\r\n</head>\r\n<body>\r\n[!--temp.header--]\r\n    <section class=\\\\\"center clearfix\\\\\">\r\n        <div class=\\\\\"sec-item left\\\\\" style=\\\\\"width: 19%;\\\\\">\r\n            <div class=\\\\\"sec-item-title\\\\\">\r\n                <img src=\\\\\"[!--news.url--]skin/default/images/yms_08.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;margin-top: 13px;\\\\\">\r\n                <p class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;\\\\\">关于我们 About us</p>\r\n            </div>\r\n            <div class=\\\\\"about-list\\\\\">\r\n                <ul>\r\n                    <li><a href=\\\\\"[!--news.url--]brief.html\\\\\">公司简介</a></li>\r\n                    <li><a href=\\\\\"[!--news.url--]culture.html\\\\\">企业文化</a></li>\r\n                    <li><a href=\\\\\"/tuanduifengcai/\\\\\">团队风采</a></li>\r\n                    <li><a href=\\\\\"/zizhirongyu/\\\\\">资质荣誉</a></li>\r\n                    <li><a href=\\\\\"/shipinzhanting/\\\\\">视频展厅</a></li>\r\n                </ul>\r\n            </div>\r\n            <img src=\\\\\"[!--news.url--]skin/default/images/left.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" style=\\\\\"margin-top: 10px;\\\\\">\r\n        </div>\r\n        <div class=\\\\\"about-right left\\\\\">\r\n            <div class=\\\\\"about-right-title\\\\\">\r\n                <p>[!--pagename--]</p>\r\n            </div>\r\n            <div class=\\\\\"about-content\\\\\">\r\n                [!--pagetext--]\r\n            </div>\r\n            <div class=\\\\\"totop right\\\\\"></div>\r\n        </div>\r\n    </section>\r\n    <ul class=\\\\\"index\\\\\">\r\n        <li></li>\r\n    </ul>\r\n    <ul class=\\\\\"indexx\\\\\">\r\n    </ul>\r\n[!--temp.footer--]\r\n</body>\r\n</html>');");
E_D("replace into `ymskj_enewspagetemp` values('4','联系我们','<!DOCTYPE html>\r\n<html lang=\\\\\"zh-CN\\\\\">\r\n<head>\r\n<meta http-equiv=\\\\\"Content-Type\\\\\" content=\\\\\"text/html; charset=utf-8\\\\\" />\r\n<title>[!--pagetitle--]</title>\r\n<meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\" />\r\n<meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/base.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<link href=\\\\\"[!--news.url--]skin/default/css/index.css\\\\\" rel=\\\\\"stylesheet\\\\\" type=\\\\\"text/css\\\\\" />\r\n<script type=\\\\\"text/javascript\\\\\" src=\\\\\"[!--news.url--]skin/default/js/tabs.js\\\\\"></script>\r\n</head>\r\n<body>\r\n[!--temp.header--]\r\n    <section class=\\\\\"center clearfix\\\\\">\r\n        <div class=\\\\\"sec-item left\\\\\" style=\\\\\"width: 19%;\\\\\">\r\n            <div class=\\\\\"sec-item-title\\\\\">\r\n                <img src=\\\\\"[!--news.url--]skin/default/images/yms_08.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;margin-top: 13px;\\\\\">\r\n                <p class=\\\\\"left\\\\\" style=\\\\\"margin-right: 10px;font-size:13px;\\\\\">联系我们 Contact us</p>\r\n            </div>\r\n            <div class=\\\\\"about-list\\\\\">\r\n                <ul>\r\n                    <li><a href=\\\\\"[!--news.url--]contact.html\\\\\">联系我们</a></li>\r\n                </ul>\r\n            </div>\r\n            <img src=\\\\\"[!--news.url--]skin/default/images/left.jpg\\\\\" alt=\\\\\"伊美时国际医药科技（北京）有限公司\\\\\" style=\\\\\"margin-top: 10px;\\\\\">\r\n        </div>\r\n        <div class=\\\\\"about-right left\\\\\">\r\n            <div class=\\\\\"about-right-title\\\\\">\r\n                <p>[!--pagename--]</p>\r\n            </div>\r\n            <div class=\\\\\"about-content\\\\\">\r\n                [!--pagetext--]\r\n            </div>\r\n            <div class=\\\\\"totop right\\\\\"></div>\r\n        </div>\r\n    </section>\r\n    <ul class=\\\\\"index\\\\\">\r\n        <li></li>\r\n        <li></li>\r\n        <li></li>\r\n        <li></li>\r\n        <li></li>\r\n        <li></li>\r\n        <li></li>\r\n    </ul>\r\n    <ul class=\\\\\"indexx\\\\\">\r\n        <li></li>\r\n    </ul>\r\n[!--temp.footer--]\r\n</body>\r\n</html>');");

@include("../../inc/footer.php");
?>